version: "3.8"

services:
  #
  # v7.9.3
  #
  elasticsearch-v7-9-3:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
    restart: always
    ports:
      - 9400:9200
      - 9500:9300
    environment:
      discovery.type: single-node
    networks:
      - elasticsearch-sandbox-v7
  kibana-v7-9-3:
    image: docker.elastic.co/kibana/kibana-oss:7.9.3
    restart: always
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-v7-9-3:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch-v7-9-3:9200
    networks:
      - elasticsearch-sandbox-v7

  #
  # v6.8.9
  #
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.9
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    networks:
      - elasticsearch-sandbox-v6
  kibana-v6-8-9:
    image: docker.elastic.co/kibana/kibana-oss:6.8.9
    restart: always
    ports:
      - 5701:5601
    networks:
      - elasticsearch-sandbox-v6
    environment:
      - xpack.monitoring.enabled=false

networks:
  elasticsearch-sandbox-v6:
    driver: bridge
  elasticsearch-sandbox-v7:
    driver: bridge
