version: "3.8"

services:
  #
  # v7.9.3
  #
  elasticsearch_v7_9_3:
    image: elasticsearch:7.9.3
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
  kibana_v7_9_3:
    image: kibana:7.9.3
    restart: always
    ports:
      - 5601:5601
    environment:
      discovery.type: single-node
  #
  # v6.8.13
  #
  elasticsearch_v6_8_13:
    image: elasticsearch:6.8.13
    restart: always
    ports:
      - 9400:9200
      - 9500:9300
    environment:
      discovery.type: single-node
  kibana_v6_8_13:
    image: kibana:6.8.13
    restart: always
    ports:
      - 5701:5601
    environment:
      discovery.type: single-node
